apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/sharjeel505/Mircro-Service-Application-Deployment.git
    targetRevision: dev
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true