apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices
  namespace: argocd
spec:
  description: Microservices deployment
  sourceRepos:
    - https://github.com/sharjeel505/Mircro-Service-Application-Deployment.git
  destinations:
    - namespace: microservices
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'